import pathlib
import numpy as np


def _psj_model_path(model_path):
    p = pathlib.Path(model_path)
    return str(p.parent / (p.stem + "_psj" + p.suffix))


class AdroitHandMixin:
    """Mixin for MyoSuite envs using the tendon-driven Adroit hand.

    Fixes three differences from muscle-driven MyoHand environments:

    - na=0: tendon actuators (dyntype="none") leave sim.data.act empty.
      get_obs_dict adds obs_dict["act"] = zeros(nu) when the parent omits it.

    - act_mag shape: parent get_reward_dict returns scalar 0 when na=0,
      causing inhomogeneous-array errors in the batched reward sum. Override
      get_reward_dict and call self._act_mag(ref) instead of the raw ternary.

    - init_qpos[0]: MyoHand parents set WRJ1=-1.57 (rad) to achieve palm-up
      via joint angle. For Adroit, palm-up is set by the XML hand-mount euler
      attribute, so WRJ1 should remain 0 (neutral). When add_wrist_pronation_supination
      is True, PSJ occupies index 0 and WRJ1 shifts to index 1; both are zeroed.

    Accepts add_wrist_pronation_supination=False in __init__. When True, swaps
    model_path to the _psj variant generated by build_adroit_assets_include().
    """

    def __init__(self, model_path, obsd_model_path=None,
                 add_wrist_pronation_supination=False, **kwargs):
        self._add_wrist_pronation_supination = add_wrist_pronation_supination
        if add_wrist_pronation_supination:
            model_path = _psj_model_path(model_path)
            if obsd_model_path is not None:
                obsd_model_path = _psj_model_path(obsd_model_path)
        super().__init__(model_path=model_path, obsd_model_path=obsd_model_path, **kwargs)

    def _setup(self, **kwargs):
        super()._setup(**kwargs)
        if self._add_wrist_pronation_supination:
            self.init_qpos[0] = 0.0  # PSJ neutral
            self.init_qpos[1] = 0.0  # WRJ1 neutral (shifted to index 1 by PSJ)
        else:
            self.init_qpos[0] = 0.0  # WRJ1 neutral

    def get_obs_dict(self, sim):
        obs_dict = super().get_obs_dict(sim)
        if "act" not in obs_dict:
            obs_dict["act"] = np.zeros(sim.model.nu)
        return obs_dict

    def _act_mag(self, ref):
        """Return act_mag shaped like ref, for use in get_reward_dict overrides.

        MyoHand: norm(act)/na — average muscle activation (act ∈ [0,1]^na).
        Adroit:  norm(ctrl)/nu — average tendon effort   (ctrl ∈ [-1,0]^nu).

        All Adroit actuators have ctrlrange="-1 0", so ctrl=0 is slack (zero
        effort) and ctrl=-1 is maximum tension. This directly parallels the
        muscle activation penalty: same scale, same semantics.

        norm(ctrl)/nu is NOT the same as norm(action)/nu when normalize_act=True
        because the agent action ∈ [-1,1] is mapped to ctrl = 0.5*(action-1).

        Also fixes the na=0 shape issue: parent classes return scalar 0 which
        causes np.sum([..., 0, ...], axis=0) to fail when other reward terms
        are batched arrays of shape (1, 1).
        """
        if self.sim.model.na != 0:
            return np.linalg.norm(self.obs_dict["act"], axis=-1) / self.sim.model.na
        return np.linalg.norm(self.sim.data.ctrl) / self.sim.model.nu * np.ones_like(ref)
