env_id: myoHandKeyTurnRandom-v0
seed: 0

total_timesteps: 7_500_000
eval_freq: 75_000
save_freq: 937_500

reward_type: dense
norm_obs: True
norm_reward: False
clip_obs: 10.0

env_kwargs:
  seed: ${env.seed}
  max_episode_steps: 200

task_variables_keys: []

camera:
  fps: 25
  type: free # 'free' or 'tracking'
  tracked_body: r_humerus # used if tracking
  lookat: [-0.220, -0.47, 1.440] # used if free
  distance: 0.6
  azimuth: 90
  elevation: -45